import "../styles/reset.css";
import "../styles/globals.css";
import styles from "./app.module.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.bodyBG}>{children}</body>
    </html>
  );
}
